name: pages-build-deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    # Ensure the `docs` directory exists
    - name: Create docs directory
      run: mkdir -p docs
    
    - name: Build Jekyll site
      run: |
        bundle install
        bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
